"""Web Research and Deep Search capabilities for AXON CLI."""

from __future__ import annotations

import html.parser
import json
import urllib.request
import urllib.parse
import re
from pathlib import Path


class HTMLToTextParser(html.parser.HTMLParser):
    def __init__(self):
        super().__init__()
        self.text_parts = []
        self.hide_content = False

    def handle_starttag(self, tag, attrs):
        if tag in {"script", "style", "head", "title", "nav", "footer", "header", "iframe", "noscript"}:
            self.hide_content = True
        elif tag == "p":
            self.text_parts.append("\n")
        elif tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            self.text_parts.append("\n\n# ")

    def handle_endtag(self, tag):
        if tag in {"script", "style", "head", "title", "nav", "footer", "header", "iframe", "noscript"}:
            self.hide_content = False
        elif tag == "p":
            self.text_parts.append("\n")

    def handle_data(self, data):
        if not self.hide_content:
            text = data.strip()
            if text:
                self.text_parts.append(text + " ")

    def get_text(self):
        # Clean up consecutive whitespaces/newlines
        raw = "".join(self.text_parts).strip()
        return re.sub(r"\n{3,}", "\n\n", raw)


def read_webpage(url: str) -> str:
    """Fetch HTML from a URL and return its clean text representation."""
    clean_url = url.strip()
    if not clean_url.startswith(("http://", "https://")):
        return "Error: URL must start with http:// or https://"
    
    try:
        req = urllib.request.Request(
            clean_url,
            headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            }
        )
        with urllib.request.urlopen(req, timeout=15) as response:
            html_bytes = response.read()
            encoding = response.headers.get_content_charset() or "utf-8"
            html_text = html_bytes.decode(encoding, errors="ignore")
            
        parser = HTMLToTextParser()
        parser.feed(html_text)
        text = parser.get_text()
        
        # Max limit to prevent context overflow in LLM
        max_chars = 15000
        if len(text) > max_chars:
            text = text[:max_chars] + f"\n\n... [content truncated; total size: {len(text)} chars]"
            
        return text if text else "Loaded webpage, but no readable text was extracted."
    except Exception as exc:
        return f"Error loading webpage: {exc}"


def deep_search(query: str, max_depth: int = 3) -> str:
    """Perform a multi-step Deep Search: search, extract top links, read contents, and synthesize a report."""
    q = query.strip()
    if not q:
        return "Error: search query is required."
        
    try:
        from ddgs import DDGS
    except ImportError:
        return "Error: ddgs is not installed. Run: pip install ddgs"

    report_lines = [
        f"# Deep Search Research Report: '{q}'",
        "*(Automatically generated by AXON Multi-Step Web Researcher)*\n"
    ]

    try:
        # Step 1: Initial search
        with DDGS() as ddgs:
            search_results = list(ddgs.text(q, max_results=5))
            
        if not search_results:
            return f"Deep Search: No initial web results found for: {q}"
            
        report_lines.append("## Search Results & Web Links")
        links_to_read = []
        for idx, item in enumerate(search_results, start=1):
            title = item.get("title") or "(no title)"
            href = item.get("href") or item.get("link") or ""
            body = item.get("body") or item.get("snippet") or ""
            report_lines.append(f"{idx}. **{title}**")
            report_lines.append(f"   URL: {href}")
            report_lines.append(f"   Snippet: {body}\n")
            if href and len(links_to_read) < max_depth:
                links_to_read.append((title, href))
                
        # Step 2: Read top links and extract snippets matching query terms
        report_lines.append("## Detailed Website Investigations")
        
        # Build query keywords for basic keyword matching to find relevant paragraphs
        keywords = [w.lower() for w in re.findall(r"\w{4,}", q)]
        
        for idx, (title, url) in enumerate(links_to_read, start=1):
            report_lines.append(f"### Source {idx}: {title}")
            report_lines.append(f"URL: {url}")
            
            content = read_webpage(url)
            if content.startswith("Error"):
                report_lines.append(f"⚠️ *Could not read site: {content}*\n")
                continue
                
            # Search for relevant paragraphs containing keywords
            paragraphs = content.split("\n")
            matched_paragraphs = []
            for p in paragraphs:
                p_clean = p.strip()
                if not p_clean or len(p_clean) < 40:
                    continue
                # Score paragraph based on keyword matches
                p_lower = p_clean.lower()
                score = sum(1 for kw in keywords if kw in p_lower)
                if score > 0:
                    matched_paragraphs.append((score, p_clean))
                    
            # Sort by relevance score
            matched_paragraphs.sort(key=lambda x: x[0], reverse=True)
            
            if matched_paragraphs:
                report_lines.append("Key findings extracted:")
                for _, text in matched_paragraphs[:3]:
                    report_lines.append(f"- *{text}*")
                report_lines.append("")
            else:
                # Fallback: first 500 characters of clean text
                snippet = content[:500].strip().replace("\n", " ")
                report_lines.append(f"Preview: {snippet}...\n")
                
        return "\n".join(report_lines)
    except Exception as exc:
        return f"Error running Deep Search: {exc}"
