# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Core.AXON
PackageVersion: 1.0.1
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - axon
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  Interactive: /SP-
ReleaseDate: 2026-06-15
Installers:
  - Architecture: x64
    InstallerUrl: https://runaxon.xyz/downloads/AXON_Setup_v1.0.1.exe
    InstallerSha256: 2CF9560AEDEDFEC798533EC481F6DCF27153798C419B85E53C75FAB0F61C9FC8
    InstallerSwitches:
      Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
      SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
AppsAndFeaturesEntries:
  - DisplayName: AXON
    Publisher: AXON Core Team
ManifestType: installer
ManifestVersion: 1.12.0
