from __future__ import annotations

from typing import Protocol


class UIOutput(Protocol):
    """Protocol for decoupling core logic from terminal rendering."""

    def set_model(self, model: str) -> None: ...

    def set_status(self, status: str) -> None: ...

    def add_user_message(self, content: str) -> None: ...

    def add_assistant_message(self, content: str) -> None: ...

    def add_system_message(self, content: str) -> None: ...

    def clear_messages(self) -> None: ...

    def refresh(self) -> None: ...

    def stream_begin(self) -> None: ...

    def stream_update(self, content: str) -> None: ...

    def stream_end(self, content: str) -> None: ...
